object Versions {
  val cats                = "2.7.0"
  val catsEffect          = "3.3.4"
  val disciplineMunit     = "1.0.9"
  val flyway              = "8.4.4"
  val hikari              = "5.0.1"
  val logback             = "1.2.10"
  val munit               = "0.7.29"
  val postgresql          = "42.3.1"
  val quartz              = "2.3.2"
  val scalatest           = "3.2.10"
  val scalacheckShapeless = "1.3.0"
  val scalatestScalacheck = "3.2.10.0"
  val scalamock           = "5.2.0"
  val shapeless2          = "2.3.7"
  val shapeless3          = "3.0.3"
  val testContainers      = "0.39.12"
}
