object Versions {
  val cats                = "2.6.1"
  val catsEffect          = "3.2.9"
  val collectionCompat    = "2.5.0"
  val disciplineMunit     = "1.0.9"
  val flyway              = "8.0.0"
  val hikari              = "5.0.0"
  val logback             = "1.2.6"
  val munit               = "0.7.29"
  val postgresql          = "42.2.24"
  val quartz              = "2.3.2"
  val scalatest           = "3.2.10"
  val scalacheckShapeless = "1.3.0"
  val scalatestScalacheck = "3.2.10.0"
  val scalamock           = "5.1.0"
  val shapeless           = "2.3.7"
  val testContainers      = "0.39.8"
}
