object Versions {
  val catsEffect          = "3.1.1"
  val collectionCompat    = "2.4.4"
  val extruder            = "0.11.0"
  val flyway              = "7.10.0"
  val fs2                 = "3.0.4"
  val hikari              = "3.4.5"
  val logback             = "1.2.3"
  val postgresql          = "42.2.18"
  val quartz              = "2.3.2"
  val scalatest           = "3.2.9"
  val scalatestScalacheck = "3.2.9.0"
  val scalamock           = "5.1.0"
  val testContainers      = "0.39.5"
}
