name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10

    - name: Cache Coursier dependencies
      uses: actions/cache@v1
      with:
       path: ~/.cache/coursier
       key: ${{ runner.os }}-${{ github.ref }}-coursier
       restore-keys: |
        ${{ runner.os }}-${{ github.ref }}-coursier

    - name: Cache Ivy dependencies
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-${{ github.ref }}-ivy2
        restore-keys: |
         ${{ runner.os }}-${{ github.ref }}-ivy2

    - name: Tests
      run: sbt -J-Xms256m -J-Xmx1G buildFs2Quartz
