jobs:
  build:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.1.0"
      - name: java 11 setup
        uses: "olafurpg/setup-scala@v10"
        with:
          java-version: '11'
      - uses: "olafurpg/setup-gpg@v3"
      - env:
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"
          PGP_SECRET: "${{ secrets.PGP_SECRET }}"
          SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
        name: "Publish ${{ github.ref }}"
        run: sbt ci-release
name: Release
on:
  push:
    branches:
      - master
    tags:
      - "*"
