name: Release Drafter

on:
  push:
    branches:
#      - master
      - __wibble-non-existent__

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo Skipping Release Drafter

#jobs:
#  update_release_draft:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: release-drafter/release-drafter@v5.11.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
